# Generated by Django 4.2.13 on 2025-07-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_head_office', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheque.project')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_number', models.CharField(max_length=20, unique=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed')], max_length=50)),
                ('approved_by', models.CharField(choices=[('Head Sir', 'Head Sir'), ('Madam', 'Madam'), ('Saad', 'Saad'), ('Abdullah', 'Abdullah')], max_length=100)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], max_length=10)),
                ('cheque_date', models.DateField()),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('bill_available', models.BooleanField(default=False)),
                ('shared_on_group', models.BooleanField(default=False)),
                ('bill_attachment', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheque.project')),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheque.employee')),
            ],
        ),
    ]
