# Generated by Django 5.2.4 on 2025-07-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_number', models.CharField(max_length=20, unique=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='not_started', max_length=50)),
                ('responsible_person', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], max_length=10)),
                ('cheque_date', models.DateField()),
                ('received_by', models.CharField(max_length=100)),
                ('bill_available', models.BooleanField(default=False)),
                ('shared_on_group', models.BooleanField(default=False)),
                ('bill_attachment', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
