# Generated by Django 4.2.13 on 2025-07-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
