# Generated by Django 4.2.13 on 2025-07-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheque', '0002_alter_cheque_cheque_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='other_responsible_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cheque.employee'),
        ),
    ]
